version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/hack/controller-gen"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/hack/diegen"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/hack/goimports"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/hack/imgpkg"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/hack/kapp"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/hack/kbld"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/hack/ko"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/hack/kustomize"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
