# This configuration is for teaching kustomize how to update name ref and var substitution 
varReference:
- kind: MutatingWebhookConfiguration
  group: admissionregistration.k8s.io
  path: webhooks/namespaceSelector/matchExpressions/values
- kind: ValidatingWebhookConfiguration
  group: admissionregistration.k8s.io
  path: webhooks/namespaceSelector/matchExpressions/values

