---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-servicebinding-io-v1beta1-clusterworkloadresourcemapping
  failurePolicy: Fail
  name: vclusterworkloadresourcemapping.kb.io
  rules:
  - apiGroups:
    - servicebinding.io
    apiVersions:
    - v1alpha3
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterworkloadresourcemappings
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-servicebinding-io-v1beta1-servicebinding
  failurePolicy: Fail
  name: vservicebinding.kb.io
  rules:
  - apiGroups:
    - servicebinding.io
    apiVersions:
    - v1alpha3
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicebindings
  sideEffects: None
