# permissions for end users to edit clusterworkloadresourcemappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterworkloadresourcemapping-editor-role
rules:
- apiGroups:
  - servicebinservicebinding.io
  resources:
  - clusterworkloadresourcemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicebinding.io
  resources:
  - clusterworkloadresourcemappings/status
  verbs:
  - get
