# permissions for end users to edit servicebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicebinding-editor-role
rules:
- apiGroups:
  - servicebinding.io
  resources:
  - servicebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicebinding.io
  resources:
  - servicebindings/status
  verbs:
  - get
